jobs:
  gradle_tasks:
    name: Gradle Tasks
    needs: gradle_validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Android JDK environment
      uses: actions/setup-java@v3.11.0
      with:
        distribution: adopt
        java-package: jdk
        java-version: '11'
    - continue-on-error: true
      name: Run Checkstyle
      run: ./gradlew checkstyle
    - continue-on-error: true
      name: "Run Unit Tests \u2014 RxAndroidBle: RxJava2"
      run: ./gradlew :rxandroidble:testReleaseUnitTest
    - continue-on-error: true
      name: "Run Unit Tests \u2014 MockClient: RxJava2"
      run: ./gradlew :mockrxandroidble:testReleaseUnitTest
    - continue-on-error: true
      name: "Run Unit Tests \u2014 RxAndroidBle: RxJava3"
      run: ./gradlew :rxandroidble3:testReleaseUnitTest
    - continue-on-error: true
      name: "Run Unit Tests \u2014 MockClient: RxJava3"
      run: ./gradlew :mockrxandroidble3:testReleaseUnitTest
    - continue-on-error: true
      name: "Run Unit Tests \u2014 Sample Kotlin"
      run: ./gradlew :sample-kotlin:testReleaseUnitTest
  gradle_validation:
    name: Validate Gradle Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Validate
      uses: gradle/wrapper-validation-action@v1
name: Gradle Actions
on:
  repository_dispatch:
    types: trigger-ga___gradle-actions.yml
